# .streamlit/config.toml

[theme]
base = "dark"
primaryColor = "#1e90ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"

[global]
developmentMode = false

[server]
port = 8501
